name: Hostinger_Deploy

on:
  push:
    branches: [ "msater" ]
  pull_request:
    branches: [ "msater" ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -p ${{ secrets.REMOTE_PORT }} ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy PHP to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            cd domains
            cd srke.co.in
            cd public_html
            git pull origin
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
            php composer.phar update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            php artisan optimize

      - name: Copy Build Files to Target Server
        run: |
          rsync -r -e "ssh -p ${{ secrets.REMOTE_PORT }}" ${{ github.workspace }}/public/build/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:~/domains/cortexitsolution.com/public_html/measypro/public/build/
